In [21]:
from starter_code_for_reading_input_data.starter_code.wsj_loader import WSJ

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
loader = WSJ()

In [5]:
loader = WSJ()

In [13]:
X.shape

(1103,)

In [15]:
y.shape

(1103,)

In [16]:
y[0].shape

(388,)

In [153]:
class NeuralNet():

    def __init__(self):

        self.parameters = None
        self.L = None
        self.A1 = None
        self.Z = None



    # Inializing parameters 
    def initialize_para(self, layer_dim):


        """ 
        Arguments:
        layer_dim : list containing dimensions of each layer 
        
        Returns:
        parameters: dictionary containing weights for each layer
        """

        np.random.seed(10)

        self.parameters = {}
        self.L = len(layer_dim)
        
        # creatinig random weights for each layer
        for l in range(1, self.L):
            self.parameters["W"+str(l)] = np.random.randn(layer_dim[l], layer_dim[l-1]+1)*0.01
            # multiplying with 0.01 to keep weights low
    
        return self.parameters


    def single_forward_prop(self, A, W):
        """
        Arguments:
        A : Activations/inputs from previous layer
        W : weights for this particular hidden layer

        Returns:
        z : inputs for the next activation function
        """
         
        self.A1 = np.concatenate(([1], A), axis=0)
        self.Z = np.dot(W, self.A1.T)

        return self.Z


    def single_activation_forward(self, A_prev, W, activation):

        self.Z = self.single_forward_prop(A_prev, W)

        # for sigmoid activation
        if activation == "sigmoid":
            self.A = 1/(1+np.exp(-self.Z)) 
         

        # for relu activation
        elif activation == "relu":
            self.A = np.maximum(0, self.Z)
            assert(A.shape == self.Z.shape)


        # for tanh activation 
        elif activation == "tanh":
            self.A = (np.exp(self.Z)-np.exp(-self.Z))/(np.exp(self.Z)+np.exp(-self.Z))


        return self.A


In [154]:
np.concatenate(([1], X[0][0]), axis=0)

array([ 1.00000000e+00, -2.77605915e+00, -1.06537542e+01, -9.39956951e+00,
       -1.01375580e-02, -8.18525314e+00, -2.07609901e+01, -1.52976494e+01,
       -2.93809967e+01, -3.73934135e+01, -2.62839699e+01, -4.26705170e+01,
       -2.20472641e+01, -1.71820831e+01, -1.58334255e+00, -2.82403421e+00,
       -4.57401371e+00, -2.99919939e+00, -2.17327547e+00, -2.73924732e+00,
       -1.06188917e+00, -1.53447104e+00, -6.87636375e-01, -2.67269611e+00,
       -1.67127037e+00, -1.48908615e+00, -8.12202930e-01, -5.70705891e-01,
       -8.22215557e-01, -9.71503735e-01, -3.02924156e-01, -4.80173111e-01,
       -7.18064308e-01, -1.05712700e+00, -1.57896519e-01, -8.74900818e-02,
       -2.37556458e-01,  1.35851860e-01,  2.36355305e-01, -5.80593109e-01,
       -8.17158699e-01])

In [155]:
nn = NeuralNet()

In [156]:
para = nn.initialize_para([40,20,10])

In [157]:
z = nn.single_forward_prop(X[0][0], para["W1"])

In [158]:
z

array([-0.4202499 , -0.20602516,  0.10836536,  0.3580392 , -0.00441877,
        0.31487566, -0.55898538, -0.56290286, -0.62026683,  0.63882793,
       -0.31193157,  0.05880023, -0.91118284, -0.71227552, -0.72184054,
       -0.69482678,  0.78380848,  0.76264104, -0.86380065,  1.18830997])

In [165]:
A = nn.single_activation_forward(X[0][0], para["W1"], "relu")

In [166]:
A

array([0.        , 0.        , 0.10836536, 0.3580392 , 0.        ,
       0.31487566, 0.        , 0.        , 0.        , 0.63882793,
       0.        , 0.05880023, 0.        , 0.        , 0.        ,
       0.        , 0.78380848, 0.76264104, 0.        , 1.18830997])

In [161]:
A = nn.single_activation_forward(X[0][0], para["W1"], "tanh")

In [162]:
A

array([-0.39714094, -0.20315881,  0.10794317,  0.34348574, -0.00441874,
        0.30486614, -0.50722424, -0.51012806, -0.55131378,  0.56410097,
       -0.3021933 ,  0.05873255, -0.72169949, -0.61210177, -0.61804808,
       -0.60107386,  0.65488724,  0.64262996, -0.69821069,  0.83005399])